/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FoodRouteImport } from './routes/food'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TraditionsRouteImport } from './routes/traditions'
import { Route as AuthenticatedCollectionRouteImport } from './routes/_authenticated.collection'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as CountrySlugRouteImport } from './routes/country.$slug'
import { Route as FestivalsIndexRouteImport } from './routes/festivals.index'
import { Route as FestivalsSlugRouteImport } from './routes/festivals.$slug'
import { Route as StoriesIndexRouteImport } from './routes/stories.index'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TraditionsRoute = TraditionsRouteImport.update({
  id: '/traditions',
  path: '/traditions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCollectionRoute = AuthenticatedCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const CountrySlugRoute = CountrySlugRouteImport.update({
  id: '/country/$slug',
  path: '/country/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalsIndexRoute = FestivalsIndexRouteImport.update({
  id: '/festivals/',
  path: '/festivals/',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalsSlugRoute = FestivalsSlugRouteImport.update({
  id: '/festivals/$slug',
  path: '/festivals/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/stories/$slug',
  path: '/stories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/food': typeof FoodRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/traditions': typeof TraditionsRoute
  '/collection': typeof AuthenticatedCollectionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/country/$slug': typeof CountrySlugRoute
  '/festivals/$slug': typeof FestivalsSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/festivals/': typeof FestivalsIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/food': typeof FoodRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/traditions': typeof TraditionsRoute
  '/collection': typeof AuthenticatedCollectionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/country/$slug': typeof CountrySlugRoute
  '/festivals/$slug': typeof FestivalsSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/festivals': typeof FestivalsIndexRoute
  '/stories': typeof StoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/food': typeof FoodRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/traditions': typeof TraditionsRoute
  '/_authenticated/collection': typeof AuthenticatedCollectionRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/country/$slug': typeof CountrySlugRoute
  '/festivals/$slug': typeof FestivalsSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/festivals/': typeof FestivalsIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/explore'
    | '/faq'
    | '/food'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/traditions'
    | '/collection'
    | '/dashboard'
    | '/country/$slug'
    | '/festivals/$slug'
    | '/stories/$slug'
    | '/festivals/'
    | '/stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/explore'
    | '/faq'
    | '/food'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/traditions'
    | '/collection'
    | '/dashboard'
    | '/country/$slug'
    | '/festivals/$slug'
    | '/stories/$slug'
    | '/festivals'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/explore'
    | '/faq'
    | '/food'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/traditions'
    | '/_authenticated/collection'
    | '/_authenticated/dashboard'
    | '/country/$slug'
    | '/festivals/$slug'
    | '/stories/$slug'
    | '/festivals/'
    | '/stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  ExploreRoute: typeof ExploreRoute
  FaqRoute: typeof FaqRoute
  FoodRoute: typeof FoodRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TraditionsRoute: typeof TraditionsRoute
  CountrySlugRoute: typeof CountrySlugRoute
  FestivalsSlugRoute: typeof FestivalsSlugRoute
  StoriesSlugRoute: typeof StoriesSlugRoute
  FestivalsIndexRoute: typeof FestivalsIndexRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traditions': {
      id: '/traditions'
      path: '/traditions'
      fullPath: '/traditions'
      preLoaderRoute: typeof TraditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/collection': {
      id: '/_authenticated/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof AuthenticatedCollectionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/country/$slug': {
      id: '/country/$slug'
      path: '/country/$slug'
      fullPath: '/country/$slug'
      preLoaderRoute: typeof CountrySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festivals/': {
      id: '/festivals/'
      path: '/festivals'
      fullPath: '/festivals/'
      preLoaderRoute: typeof FestivalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festivals/$slug': {
      id: '/festivals/$slug'
      path: '/festivals/$slug'
      fullPath: '/festivals/$slug'
      preLoaderRoute: typeof FestivalsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/stories/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCollectionRoute: typeof AuthenticatedCollectionRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCollectionRoute: AuthenticatedCollectionRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  ExploreRoute: ExploreRoute,
  FaqRoute: FaqRoute,
  FoodRoute: FoodRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TraditionsRoute: TraditionsRoute,
  CountrySlugRoute: CountrySlugRoute,
  FestivalsSlugRoute: FestivalsSlugRoute,
  StoriesSlugRoute: StoriesSlugRoute,
  FestivalsIndexRoute: FestivalsIndexRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
